spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/xiaozhi_server?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
      password: 